name: Build for Windows

on:
  push:
  #  tags:
  #    - v*
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'desktop'
        version: '5.12.10'
        modules: 'qtscript'
        arch: 'win32_msvc2017'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Configure
      run: |
        md stellarium-bin
        md build
        cd build
        md msvc
        cd msvc
        cmake -DCMAKE_INSTALL_PREFIX=D:/a/stellarium/stellarium/stellarium-bin -G "Visual Studio 15 2017" -A Win32 ../..
        cmake --build . --  /maxcpucount:4 /nologo --target stellarium-installer
    - name: show filetrees
      run: |
        ls -R .
    - uses: actions/upload-artifact@v1
      with:
        name: Debug-APP
        path: stellarium-bin
